### ISSUE TITLE
Attempt to invoke virtual method 'com.hippo.unifile.uniFile[]

### ISSUE THREAD

**Issue by melnation-com** [az4521/flashdex#1]
Hey could you allow issues in TachiyomiAZ again? can't even make pull request, and all issues are closed so no one could reply to them. no one can make anything or reply to anything in that repository. And the discord is a total chaos, no exaggeration no hyperbole, and flame baiting mods.

Anyway, there's an error "Attempt to invoke virtual method 'com.hippo.unifile.uniFile[]" while trying to download(atleast auto download) newly released chapters.

Android 5
Tachiaz version: v8.7.0-AZ
Build time 11/06/22

Extension
Mangasee 1.3.29

PS: I can visit the website fine and even logged-in, I'm not blocked or tachiyomiAZ is not blocked as of writing, I can even read the manga in the app, just not DL them for offline reading. Thanks.

**Comment by az4521** [comment]
i'll open issues, but

https://tachiyomi.org/help/guides/troubleshooting/

The Attempt to invoke virtual method' com.hippo.unifile... error can be caused by various reasons, but they all have to do with storage.

Most commonly, it is caused by full storage. Check to see if your device or SD Card is full.
Check if Tachiyomi has access to the SD card. You can enable it in Android settings for app permissions.
If you're downloading and this error pops up, that means the app might not be able to access the folder you're trying to download to. This may be because the folder is corrupted or does not exist. Use a file manager to check that the folder(s) exist and every folder in the sequence is available and accessible.
The drive you're writing to is corrupted. Check using a file manager to see if it is accessible.
